//_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
//_\source wip.tlv 47

//_\SV
`default_nettype none
module serv_alu
  #(
   parameter W = 1,
   parameter B = W-1
  )
  (
   input wire             clk,
   //State
   input wire             i_en,
   input wire             i_cnt0,
   output wire            o_cmp,
   //Control
   input wire             i_sub,
   input wire [1:0]       i_bool_op,
   input wire             i_cmp_eq,
   input wire             i_cmp_sig,
   input wire [2:0]       i_rd_sel,
   //Data
   input wire  [B:0]      i_rs1,
   input wire  [B:0]      i_op_b,
   input wire  [B:0]      i_buf,
   output wire [B:0]      o_rd);
// ---------- Generated Code Inlined Here (before 1st \TLV) ----------
// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)





//
// Signals declared top-level.
//

// For |alu$add_b.
logic [B:0] ALU_add_b_a0;

// For |alu$add_cy.
logic ALU_add_cy_a0;

// For |alu$add_cy_r.
logic [B:0] ALU_add_cy_r_n1,
            ALU_add_cy_r_a0;

// For |alu$bool_op.
logic [1:0] ALU_bool_op_a0;

// For |alu$buf.
logic [B:0] ALU_buf_a0;

// For |alu$cmp.
logic ALU_cmp_a0;

// For |alu$cmp_eq.
logic ALU_cmp_eq_a0;

// For |alu$cmp_r.
logic ALU_cmp_r_n1,
      ALU_cmp_r_a0;

// For |alu$cmp_sig.
logic ALU_cmp_sig_a0;

// For |alu$cnt0.
logic ALU_cnt0_a0;

// For |alu$en.
logic ALU_en_a0;

// For |alu$op_b.
logic [B:0] ALU_op_b_a0;

// For |alu$op_b_sx.
logic ALU_op_b_sx_a0;

// For |alu$rd.
logic [B:0] ALU_rd_a0;

// For |alu$rd_sel.
logic [2:0] ALU_rd_sel_a0;

// For |alu$result_add.
logic [B:0] ALU_result_add_a0;

// For |alu$result_bool.
logic [B:0] ALU_result_bool_a0;

// For |alu$result_eq.
logic ALU_result_eq_a0;

// For |alu$result_lt.
logic ALU_result_lt_a0;

// For |alu$result_slt.
logic [B:0] ALU_result_slt_a0;

// For |alu$rs1.
logic [B:0] ALU_rs1_a0;

// For |alu$rs1_sx.
logic ALU_rs1_sx_a0;

// For |alu$sub.
logic ALU_sub_a0;




   //
   // Scope: |alu
   //

      // Staging of $add_cy_r.
      always_ff @(posedge clk) ALU_add_cy_r_a0[B:0] <= ALU_add_cy_r_n1[B:0];

      // Staging of $cmp_r.
      always_ff @(posedge clk) ALU_cmp_r_a0 <= ALU_cmp_r_n1;



// ---------- Generated Code Ends ----------
//_\TLV
   // Connect Verilog inputs:
   //_|alu
      //_@0
         assign ALU_en_a0           = i_en;
         assign ALU_cnt0_a0         = i_cnt0;
         assign ALU_sub_a0          = i_sub;
         assign ALU_bool_op_a0[1:0] = i_bool_op;
         assign ALU_cmp_eq_a0       = i_cmp_eq;
         assign ALU_cmp_sig_a0      = i_cmp_sig;
         assign ALU_rd_sel_a0[2:0]  = i_rd_sel;
         assign ALU_rs1_a0[B:0]     = i_rs1;
         assign ALU_op_b_a0[B:0]    = i_op_b;
         assign ALU_buf_a0[B:0]     = i_buf;
   //_\source wip.tlv 7   // Instantiated from wip.tlv, 87 as: m5+serv_alu(/top)
      //_|alu
         //_@0
            //Sign-extended operands
            assign ALU_rs1_sx_a0  = ALU_rs1_a0[B] & ALU_cmp_sig_a0;
            assign ALU_op_b_sx_a0 = ALU_op_b_a0[B] & ALU_cmp_sig_a0;
   
            assign ALU_add_b_a0[B:0] = ALU_op_b_a0 ^ {W{ALU_sub_a0}};
   
            assign {ALU_add_cy_a0, ALU_result_add_a0[B:0]} = ALU_rs1_a0 + ALU_add_b_a0 + ALU_add_cy_r_a0;
   
            assign ALU_result_lt_a0 = ALU_rs1_sx_a0 + ~ ALU_op_b_sx_a0 + ALU_add_cy_a0;
   
            assign ALU_result_eq_a0 = ! (| ALU_result_add_a0) & (ALU_cmp_r_a0 | ALU_cnt0_a0);
   
            assign ALU_cmp_a0 = ALU_cmp_eq_a0 ? ALU_result_eq_a0 : ALU_result_lt_a0;
   
            /*
             The result_bool expression implements the following operations between
             i_rs1 and i_op_b depending on the value of i_bool_op
   
             00 xor
             01 0
             10 or
             11 and
   
             i_bool_op will be 01 during shift operations, so by outputting zero under
             this condition we can safely or result_bool with i_buf
             */
            assign ALU_result_bool_a0[B:0] = ((ALU_rs1_a0 ^ ALU_op_b_a0) & ~ {W{ALU_bool_op_a0[0]}}) | ({W{ALU_bool_op_a0[1]}} & ALU_op_b_a0 & ALU_rs1_a0);
   
            // relevant if W>1: result_slt[B:1] = 0
            assign ALU_result_slt_a0[B:0] = {{B{1'b0}}, ALU_cmp_r_a0 & ALU_cnt0_a0};
   
            assign ALU_rd_a0[B:0] = ALU_buf_a0 |
                       ({W{ALU_rd_sel_a0[0]}} & ALU_result_add_a0) |
                       ({W{ALU_rd_sel_a0[1]}} & ALU_result_slt_a0) |
                       ({W{ALU_rd_sel_a0[2]}} & ALU_result_bool_a0);
   
            assign ALU_add_cy_r_n1[B:0] = {{B{1'b0}}, ALU_en_a0 ? ALU_add_cy_a0 : ALU_sub_a0};
            assign ALU_cmp_r_n1         = ALU_en_a0 ? ALU_cmp_a0 : ALU_cmp_r_a0;
   //_\end_source
   // Connect Verilog outputs:
   //_|alu
      //_@0
         assign o_cmp = ALU_cmp_a0;
         assign o_rd  = ALU_rd_a0;
//_\SV
   endmodule


// Undefine macros defined by SandPiper.
`undef BOGUS_USE
